### ISSUE TITLE
About ClearSky Team

### ISSUE THREAD

**Issue by Adam1609** [ClearSkyTeam/We-Want-You#1]
Its okay for me to become a translator, i really want to translate for my server. But some of a event doesnt work so...

**Comment by aodzip** [comment]
Okay , join the telegram group provide on readme. md in main repo , and you will be in UE Team , just do your translate work , please do not mess up codes

**Comment by Driesboy** [comment]
i will join the team

**Comment by haniokasai** [comment]
can i join ClearSky Team?

**Comment by Driesboy** [comment]
I will join to

Dries C
Op 20-feb.-2016 12:04 schreef "haniokasai" <notifications@github.com>:

**Comment by haniokasai** [comment]
:)

**Comment by aodzip** [comment]
What do you want work on?

**Comment by haniokasai** [comment]
ClearSky isnt known well in japan. so　I want to spread ClearSky in japan.
i will  translate it into Japanese
i know linux, php..

**Comment by aodzip** [comment]
Can you also code for the server? and fix bugs?

**Comment by haniokasai** [comment]
yeah. but i dont know about packet.....

**Comment by aodzip** [comment]
Good , I send an invention to your github account

**Comment by haniokasai** [comment]
Thanks a lot <3<3<3<3

**Comment by haniokasai** [comment]
and followed you at weibo!

**Comment by aodzip** [comment]
My weibo account isn't active , I use Twitter more...

**Comment by aodzip** [comment]
And , please join the Telegram group provide in main repo's readme.md .

**Comment by aodzip** [comment]
And , what about you @Driesboy

**Comment by Driesboy** [comment]
i am 12

**Comment by Driesboy** [comment]
i make plugins

**Comment by CreeperGo** [comment]
Can I join the team?  :)

**Comment by MasterWolf** [comment]
Can i join? I can be a translator! @aodzip and @thebigsmileXD saw my work. (I translated readme)

**Comment by AmiroEmad** [comment]
@aodzip hello can i join i will work on clearsky installer and i will develop a website for clear sky

**Comment by Gamecrafter** [comment]
@MasterWolf @CreeperGo @Adam1609 I wouldn't try to join if I were you. You won't like some of the people you work with.

**Comment by robske110** [comment]
Ah, yeah and why exactly?
I don't think you have even once talked to me.
Neither to dan or aodzip

**Comment by Gamecrafter** [comment]
@robske110 I don't need to talk to you guys to know how you work. You're no problem, you're not overly aggressive, aodzip is okay too, I don't see any problems with him. But Dan? I don't need to directly interact with him to know how he is, I can just read around and see how he interacts with other people. He's had a history with being aggressive at times even when no one is aggressive to him.

**Comment by TonyWAV** [comment]
can i join clearsky too

**Comment by TheProest35YT** [comment]
Im a Translator

**Comment by TheProest35YT** [comment]
I can translate 한국어 korean

**Comment by robske110** [comment]
just do PRs

**Comment by TheProest35YT** [comment]
Whats PR

**Comment by Aericio** [comment]
PullRequests - https://github.com/ClearSkyTeam/ClearSky/pulls
