### ISSUE TITLE
I-Want-To-Join

### ISSUE THREAD

**Issue by Survingo** [ClearSkyTeam/We-Want-You#3]
ummm....

hi :D 

I just ask if I could join.
If anyone doesn't know me, I am the :de: german coder fixing bugs, adding things and else.

:+1:

**Comment by thebigsmileXD** [comment]
@aodzip I know him from the forums.

Well, tell us exactly what you like to do: core work or User suggestions etc

**Comment by Survingo** [comment]
I could code for the server and fix bugs, issues..
Maybe I don't really know all about the Packets, but that shouldn't be such a big problem, or?

**Comment by Survingo** [comment]
I could also develop android like something ClearSky for Android

**Comment by robske110** [comment]
Hmm, I don't have the rights to add sou but we could use any helping hand...
Can you start off with some PRs?

**Comment by thebigsmileXD** [comment]
omg german coders is such a noob team..

**Comment by Gamecrafter** [comment]
@thebigsmileXD You people are German? :O

**Comment by robske110** [comment]
I don't know why he declined you...

**Comment by Gamecrafter** [comment]
@robske110 Are you talking about declining him, or me?

**Comment by robske110** [comment]
The last message was to you
