### ISSUE TITLE
You want me

### ISSUE THREAD

**Issue by Gamecrafter** [ClearSkyTeam/We-Want-You#6]
@aodzip Hello, I'd like to join (again, I think). I think you guys invited me a few months ago, but I declined. I've changed my mind about it. If I were to join, I'd do some web development, and some work on ClearSky. Lately, I've felt my PHP skills deteriorating, I need something so I can keep practicing it. So would you guys like to recruit me? It's okay if you guys don't.

**Comment by robske110** [comment]
I don't have the roghts to add you, but I'll talk to the team.
Until then you could start off with some PRs :)

**Comment by thebigsmileXD** [comment]
We will NOT accept YOU.
